### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Patsch36** [jliocsar/better-ts-errors#6] opened 2023-08-24 13:54 UTC
- Issue Type: `Performance`
- Extension Name: `better-ts-errors`
- Extension Version: `1.7.7`
- OS Version: `Darwin arm64 22.5.0`
- VS Code version: `1.81.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/wj/r6w3fz4d27sb_9h417chvttw0000gn/T/better-ts-errors.better-ts-errors-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by jliocsar** [comment] 2023-08-24 14:23
Hey, so sorry about this, I'm pushing a temporary fix for it.
Are you currently using any other extension that adds information on hover such as ESLint? I'm trying to figure out the root cause of this issue.

Closing this so we can keep track of the issue with #5.

**Closed as completed** 2023-08-24 14:31 UTC
